{% set name = "nilearn" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nilearn-{{ version }}.tar.gz
  sha256: 03ef4da72d1ae87b2e3f28b771dc7e05464aa179626e57c300595625a8654273

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.7
    - joblib >=1.0.0
    - lxml
    - nibabel >=3.2.0
    - numpy >=1.19.0
    - pandas >=1.1.5
    - requests >=2.25.0
    - scikit-learn >=1.0.0
    - scipy >=1.6.0
    - packaging


test:
  imports:
    - nilearn
  # we cannot use pip-check b/c scikit-learn is found by its import name sklearn :-(
  # requires:
  #   - pip
  # commands:
  #   - pip check

about:
  home: https://nilearn.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Statistical learning for neuroimaging in Python

extra:
  recipe-maintainers:
    - lesteve
    - ocefpaf
    - GaelVaroquaux
    - KamalakerDadi
