{% set version = "0.7.1" %}

package:
  name: nilearn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nilearn/nilearn-{{ version }}.tar.gz
  sha256: 8b1409a5e1f0f6d1a1f02555c2f11115a2364f45f1e57bcb5fb3c9ea11f346fa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - joblib >=0.12
    - nibabel >=2.0.2
    - numpy >=1.11
    - pandas >=0.18.0
    - requests >=2
    - scikit-learn >=0.19
    - scipy >=0.19

test:
  imports:
    - nilearn
  # we cannot use pip-check b/c scikit-learn is found by its import name sklearn :-(
  # requires:
  #   - pip
  # commands:
  #   - pip check

about:
  home: https://nilearn.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Statistical learning for neuroimaging in Python

extra:
  recipe-maintainers:
    - lesteve
    - ocefpaf
    - GaelVaroquaux
    - KamalakerDadi
