{% set version = "0.6.1" %}

package:
  name: nilearn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nilearn/nilearn-{{ version }}.tar.gz
  sha256: e18f029e915232450e6d3574a2253d8b6cb2d7bbea521118854a1e2ea67c8242

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python >=3.5
    - pip
    - numpy
    - scipy
    - scikit-learn
    - joblib
    - nibabel
  run:
    - python >=3.5
    - numpy
    - scipy
    - scikit-learn
    - nibabel
    - joblib
    - matplotlib

test:
  imports:
    - nilearn

about:
  home: https://nilearn.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Statistical learning for neuroimaging in Python'

extra:
  recipe-maintainers:
    - lesteve
    - ocefpaf
    - GaelVaroquaux
    - KamalakerDadi
