{% set name = "nilearn" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nilearn-{{ version }}.tar.gz
  sha256: 2c3cf94b0f77461c242baf61b9efb4dd68dd4e2fc4eab19ae93e978b0c45b9b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - jinja2 >=3.1.6
    - python >={{ python_min }}
    - joblib >=1.2.0
    - lxml
    - nibabel >=5.2.0
    - numpy >=1.26.0
    - pandas >=2.3.0
    - requests >=2.33.0
    - scikit-learn >=1.5.0,!=1.7.0,!=1.9.0
    - scipy >=1.11.1
    - packaging >=26.0.0


test:
  imports:
    - nilearn
  requires:
    - python {{ python_min }}
    - pip
  # we cannot use pip-check b/c scikit-learn is found by its import name sklearn :-(
  # commands:
  #   - pip check

about:
  home: https://nilearn.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Statistical learning for neuroimaging in Python

extra:
  recipe-maintainers:
    - lesteve
    - ocefpaf
    - GaelVaroquaux
    - KamalakerDadi
