{% set version = "0.10.1" %}

package:
  name: nilearn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nilearn/nilearn-{{ version }}.tar.gz
  sha256: 928a364e7ed77d15d02b7f227197ea7c78f44f2fe780feb555d6d7cf9232f846

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - joblib >=1.0.0
    - lxml
    - nibabel >=3.0.0
    - numpy >=1.19.0
    - pandas >=1.1.5
    - requests >=2.25.0
    - scikit-learn >=1.0.0
    - scipy >=1.6.0


test:
  imports:
    - nilearn
  # we cannot use pip-check b/c scikit-learn is found by its import name sklearn :-(
  # requires:
  #   - pip
  # commands:
  #   - pip check

about:
  home: https://nilearn.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Statistical learning for neuroimaging in Python

extra:
  recipe-maintainers:
    - lesteve
    - ocefpaf
    - GaelVaroquaux
    - KamalakerDadi
