{% set name = "nilearn" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nilearn-{{ version }}.tar.gz
  sha256: 0a2606b2d47206d5af25d896854fe85f03d84db6a56e00326028da6f08c82cf7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - jinja2 >=3.1.2
    - python >={{ python_min }}
    - joblib >=1.2.0
    - lxml
    - nibabel >=5.2.0
    - numpy >=1.22.4
    - pandas >=2.2.0
    - requests >=2.30.0
    - scikit-learn >=1.4.0
    - scipy >=1.9.0
    - packaging


test:
  imports:
    - nilearn
  requires:
    - python {{ python_min }}
    - pip
  # we cannot use pip-check b/c scikit-learn is found by its import name sklearn :-(
  # commands:
  #   - pip check

about:
  home: https://nilearn.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Statistical learning for neuroimaging in Python

extra:
  recipe-maintainers:
    - lesteve
    - ocefpaf
    - GaelVaroquaux
    - KamalakerDadi
