{% set version = "0.5.0" %}

package:
  name: nilearn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nilearn/nilearn-{{ version }}.tar.gz
  sha256: 085cd4f7c19a47ed9d951c853223190b9fb0dbddeaeedf8f86dfa9c53d6492ca

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - numpy
    - scipy
    - scikit-learn
    - nibabel
  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - nibabel
    - matplotlib

test:
  imports:
    - nilearn

about:
  home: https://nilearn.github.io
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'Statistical learning for neuroimaging in Python'

extra:
  recipe-maintainers:
    - lesteve
    - ocefpaf
    - GaelVaroquaux
    - KamalakerDadi
