{% set version = "0.6.2" %}

package:
  name: nilearn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nilearn/nilearn-{{ version }}.tar.gz
  sha256: cfc6cfda59a6f4247189f8ccf92e364de450460a15c0ec21bdb857c420dd198c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.5
    - pip
    - numpy
    - scipy
    - scikit-learn
    - joblib
    - nibabel
  run:
    - python >=3.5
    - numpy
    - scipy
    - scikit-learn
    - nibabel
    - joblib
    - matplotlib-base

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - nilearn

about:
  home: https://nilearn.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Statistical learning for neuroimaging in Python

extra:
  recipe-maintainers:
    - lesteve
    - ocefpaf
    - GaelVaroquaux
    - KamalakerDadi
