{% set name = "nilearn" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nilearn-{{ version }}.tar.gz
  sha256: a01df08fc6c8ded3cd6fb7a211634603ad46a6df780504b6d05222c2e7a972fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - joblib >=1.2.0
    - lxml
    - nibabel >=5.2.0
    - numpy >=1.22.4
    - pandas >=2.2.0
    - requests >=2.25.0
    - scikit-learn >=1.4.0
    - scipy >=1.8.0
    - packaging


test:
  imports:
    - nilearn
  requires:
    - python {{ python_min }}
    - pip
  # we cannot use pip-check b/c scikit-learn is found by its import name sklearn :-(
  # commands:
  #   - pip check

about:
  home: https://nilearn.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Statistical learning for neuroimaging in Python

extra:
  recipe-maintainers:
    - lesteve
    - ocefpaf
    - GaelVaroquaux
    - KamalakerDadi
