{% set version = "0.10.0" %}

package:
  name: nilearn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nilearn/nilearn-{{ version }}.tar.gz
  sha256: cc7f1068e038076527ead1bd363436f88f5e8d21e8bb57b323b30b926fc7553a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - joblib >=0.15
    - lxml
    - nibabel >=3.0.0
    - numpy >=1.18
    - pandas >=1.0
    - requests >=2
    - scikit-learn >=0.22
    - scipy >=1.5


test:
  imports:
    - nilearn
  # we cannot use pip-check b/c scikit-learn is found by its import name sklearn :-(
  # requires:
  #   - pip
  # commands:
  #   - pip check

about:
  home: https://nilearn.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Statistical learning for neuroimaging in Python

extra:
  recipe-maintainers:
    - lesteve
    - ocefpaf
    - GaelVaroquaux
    - KamalakerDadi
