{% set version = "0.6.0" %}

package:
  name: nilearn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nilearn/nilearn-{{ version }}.tar.gz
  sha256: 07eb764f2b7b39b487f806a067e394d8ebffff21f57cd1ecdb5c4030b7210210

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
    - numpy
    - scipy
    - scikit-learn
    - joblib
    - nibabel
  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - nibabel
    - joblib
    - matplotlib

test:
  imports:
    - nilearn

about:
  home: https://nilearn.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Statistical learning for neuroimaging in Python'

extra:
  recipe-maintainers:
    - lesteve
    - ocefpaf
    - GaelVaroquaux
    - KamalakerDadi
