{% set name = "nilearn" %}
{% set version = "0.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nilearn-{{ version }}.tar.gz
  sha256: 77819331314c4ca5c15c07634f69f855fafdf9add051b1882e3a600ad52757d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - joblib >=1.0.0
    - lxml
    - nibabel >=4.0.0
    - numpy >=1.19.0
    - pandas >=1.1.5
    - requests >=2.25.0
    - scikit-learn >=1.0.0
    - scipy >=1.8.0
    - packaging


test:
  imports:
    - nilearn
  # we cannot use pip-check b/c scikit-learn is found by its import name sklearn :-(
  # requires:
  #   - pip
  # commands:
  #   - pip check

about:
  home: https://nilearn.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Statistical learning for neuroimaging in Python

extra:
  recipe-maintainers:
    - lesteve
    - ocefpaf
    - GaelVaroquaux
    - KamalakerDadi
