{% set version = "0.7.0" %}

package:
  name: nilearn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nilearn/nilearn-{{ version }}.tar.gz
  sha256: e7c9df82a31319366f02919794e0ec4eacbae1fb24c41c826070c2a3acf117e6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.5
    - pip
    - numpy
    - scipy
    - scikit-learn
    - joblib
    - nibabel
  run:
    - python >=3.5
    - numpy
    - scipy
    - scikit-learn
    - nibabel
    - joblib
    - matplotlib-base

test:
  imports:
    - nilearn
  # we cannot use pip-check b/c scikit-learn is found by its import name sklearn :-(
  # requires:
  #   - pip
  # commands:
  #   - pip check

about:
  home: https://nilearn.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Statistical learning for neuroimaging in Python

extra:
  recipe-maintainers:
    - lesteve
    - ocefpaf
    - GaelVaroquaux
    - KamalakerDadi
