{% set version = "0.5.1" %}

package:
  name: nilearn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nilearn/nilearn-{{ version }}.tar.gz
  sha256: dca56e8a1f0fc6dcd1c997383187efc31788294ac6bcbbaebac2b9a962a44cbb

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - numpy
    - scipy
    - scikit-learn
    - nibabel
  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - nibabel
    - matplotlib

test:
  imports:
    - nilearn

about:
  home: https://nilearn.github.io
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'Statistical learning for neuroimaging in Python'

extra:
  recipe-maintainers:
    - lesteve
    - ocefpaf
    - GaelVaroquaux
    - KamalakerDadi
