travis:
  secure:
    BINSTAR_TOKEN: aVI26P3a21+3QY1KQJ0XWvcipoVUjrsNbB1uH2UTY8nI7k+E/YUgUBk/jfQj2m60JFITzLQ87oE2cwt98PLw76epnQXcM4t1SuBRcjxt6btKT2RkdryKSmhrQLfkbhHvwaTXX3Iv72cYbLfguILqPdjZAcQGRnRTHQkngaHqILYvwI34sYpSAbfkSPderakBsbuLJmxJ5VjCf6v6HcRese0L/4011ugD318yg/sOiPgaaNBdhh9OpnoJeW3ZiJUfGKRSw2CtnID/6U7WdPoPW7x1jSLT5LsIBY0YQx3HV3WLdBvrEVKm1B9LcJLxTo//t2vLzLl/ULfoKDTdeoga6nz/nuETk9Lg6s07qTL1JQNozlTap+PpSMa8mSLylssyE1yWz4r/LNlQGRBD2wNpr36Poj9Qb5xkwajWcoTPjXJZW8iF00+JyPWLITgc12RVCzEzQBdSlO0wlADjrXBNeyWHeU81JTEfhPV0/0bLmV5dOpn4slkSX//ul53hrZSgLNEQYetHKvJ/f+tIeqeycSiOS3ThklGM/+yMhkSVfzBl77FuyjH6RoOqZ4kYHIIKlywl/yj4qNzUUaz5x5Fa0OWS+9efO5rggm8U01rI1XiZrE3n5OD7Ef8+sIHAIF5Fli7x0wRD/lVnwN3lF0ALQDVDZUdTsJr2knD3s0ACrLo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
